### ISSUE TITLE
Post MHD To-Do + Miscellaneous Code To-Do

### ISSUE THREAD

**Issue by bcaddy** [bcaddy/cholla#11]
# Science

- [ ] Write a code paper
- [ ] Look into ParaView
- [ ] Run MHD simulations
- [ ] Contribute to BSSw?

# Code and Performance

## MHD Optizations

- [ ] Overlap kernels (specifically the grid update kernels but anything else that doesn't depend on previous kernel)
  - I could overlap the CT+magnetic update with the hydro update.
  - magnetic divergence can be overlapped
- [x] NVIDIA Compute Sanitizer to check for errors/static analyzer. RUN THIS
- [ ] If I refactor the MHD into a friend class of Grid3D I can provide an API to easily do asynchronous stuff. The various handles for syncing an be member functions, including cuda streams and MPI stuff.
  - I think all of this could be done local to the integrator without having to actually interact with Grid3D. Sync the divergence at the beginning, sync CT fields and magnetic update when needed, launch magnetic divergence checker at the end.
- See the Plank All Sky Map for a good magnetic field visualization 

## Minor Projects (days)

- [ ] Switch to using a non default stream. The default stream blocks all other streams so we probably shouldn't use it.
  - This also means that we can use multiple streams concurrently to improve performance.
- [x] Currently we use `MPI_Init`. If we ever want to do MPI calls in OpenMP parallel regions we need to use `MPI_Init_thread`
- [ ] Replace `cuda_sgn` with ternary operator
- [ ] Check which fast math options actually help
- [ ] Update testing code to use C++17 features
  - [ ] In file manipulation
  - [ ] nearlyEqualDbl should return with structured binding, maybe with a struct so that people can just use that struct??
- [x] Switch back to using GoogleTest main
- [ ] Clean up warnings
  - Make sure we're actually generating all the relevant warnings on the various compilers
- [ ] Remove `using namespace std`
- [ ] Add DeviceVector to other places
- [x] Make class for persistent communication
- [ ] Refactor the HLLD solver to use a class. That way I'm not passing around so many damn variables. This might impact performance since I might hit the limit of the size of the register. Should do profiling.
- [ ] Switch automated builds to Spack. Switch personal use too?
- [ ] Refactor HDF5 I/O to use functions for each dataset and (optionally) output ghost cells. Also, add a timer for the I/O
- [ ] Once the Occupancy API is fixed for HIP (and verified to work on AMD) try applying it to every kernel and see if it's faster

## Medium Projects (weeks)

- [ ] GitHub Action to build and deploy Cholla doxygen documentation
- [ ] Improve code reuse
- [ ] Rerunable profiling including I/O, kernels, etc
- [ ] Analysis Tools
  - Need a system for adding new things. See slide below
  - [x] Clang-Format
  - [x] Clang-Tidy
    - Start with everything turned on and turn off the stuff we don't care about or turn things on one at a time. Requires a complete list of all things to turn off and on.
  - [ ] Spell checker
  - [x] Clang static analyzer (scan-build?)
  - [ ] Valgrind or Clang/LLVM Sanitizers
  - [ ] Code coverage of CPU code
  - [ ] [GremCat](https://github.com/CAT-SDK/GremCat/)
    - lots of info and introspection including quality metrics
    - Includes MeerCat for now which provides a nice little report on PRs
- [x] Figuring out how to use a parallel debugger well and teaching the rest of us
- [ ] in-situ visualization for high temporal resolution? VisIt, Paraview, and Ascent will do this; Paraview has and NVIDIA IndeX plugin.

## Major Projects (month(s))

- [ ] Benchmarking tests. Just making sure that the code doesn't get slower. At the least we should hit the integrator, major kernels, and a couple of longer system tests where we don't check the results
- [ ] Lots more tests
  - Test for conservation across a single time step or a system test
  - Make scaffolding to generate grids and such for testing
  - Testing the ability for the code to restart
- [ ] Refactor MPI communication to use persistent communication
- [ ] Refactor MPI communication to use MPI data types instead of packing buffers manually
  - This will likely require, or benefit from, a significant refactor of the boundary conditions as well
  - This also might not be faster since GPU buffer packing is so dang fast
- [ ] Refactor boundary conditions for clarity
- [ ] Improve I/O performance with parallel I/O. Possible to gain a lot of performance here if we're careful.
  - consider switching to another HDF5 API if it supports parallel and asynchronous I/O
  - Output a lossy compressed format for science and a full quality version for checkpointing or perform lossy compression as a post processing step
- [ ] CMake??
  - Lots of new tools require it
 
![02-overview](https://user-images.githubusercontent.com/41171425/184253767-7b94213f-0aed-4d81-9149-55ecabcb7b37.png)

**Comment by bcaddy** [comment]
Moved to project boards in the main Cholla repo
